services:
  app2:
    build: .
    depends_on:
      - mongodb
    ports:
      - "127.0.0.1:8080:8080"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: caos
      MONGO_INITDB_ROOT_PASSWORD: 2025
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongodb_data_container1:/data/db

volumes:
  mongodb_data_container1: